### PR TITLE
support future syntax

### PR DESCRIPTION
**Pull request by stas-vilchik**
This PR shows the problem of supporting different TypeScript versions.

Currently we bundle the version 2.3 and use it to run the analysis. However if the analyzed project is using another version (2.4 in our case), and the code contains new syntax constructions, the analysis fails.

### CODE REVIEW

**Comment by stas-vilchik** [comment]
The solution might be to try to use typescript/tslint of the analyzed project, and fallback to the bundled versions if not possible.

**Comment by inverno** [comment]
@stas-vilchik yeah, I had tried to depend on the global typescript (not the project's tslint, since we can't assume tslint is there at all). It doesn't work without a hack and it's strongly discouraged. I see why you would use tslint as the entry point, because we can't control tslint's own dependencies without changes to the bundled tslint... I don't have a solution in mind. Will read about around when I have connectivity.

**Comment by inverno** [comment]
I created this [issue](https://github.com/SonarSource/SonarTS/issues/146) to make sure that we at least we are up-to-date by the time we release 1.0

**Comment by stas-vilchik** [comment]
superseded by #26

**Pull request closed without merging**
